### PR TITLE
Fix summary command filtering

### LINKED ISSUE #132: Summary command does not consider income entries when month filter is applied
# Issue

Currently, the `summary` command when applied with the `mo/` filter only calculates the total expenditure in the specified month. However, the total income statistic is still based on all months.

# Expected Behaviour

The total income statistic should also be calculated based on income entries in the specified month.

### PR DESCRIPTION
**Pull request by ruihan00**
Close #132 

- [x] update filter to filter income on summary command
- [x] update graph panel on summary
- [x] fix bug in lenient date parsing

### CODE REVIEW

File: src/main/java/seedu/pennywise/model/entry/Date.java [hunk 1]
```diff
@@ -6,19 +6,22 @@
...
-            "Dates should be of the format dd-mm-yyyy and it should only contain numbers";
-    public static final String VALIDATION_PATTERN = "dd-MM-yyyy";
+            "Dates should be of the format dd-mm-yyyy and it should only contain numbers,\n "
+                    + "Date must also be a valid date";
+    public static final String VALIDATION_PATTERN = "dd-MM-uuuu";
     public static final String VALIDATION_REGEX =
             "^([0-2][0-9]||3[0-1])-(0[1-9]||[1-9]||1[0-2])-([0-9][0-9])?[0-9][0-9]$";
 
-    public static final String YEAR_MONTH_PATTERN = "yyyy-MM";
+    public static final String YEAR_MONTH_PATTERN = "uuuu-MM";
```
Comment (EmilyOng) [inline src/main/java/seedu/pennywise/model/entry/Date.java:24]: Thanks for fixing the bug! https://stackoverflow.com/questions/41177442/uuuu-versus-yyyy-in-datetimeformatter-formatting-pattern-codes-in-java

File: src/main/java/seedu/pennywise/ui/MainWindow.java [hunk 2]
```diff
@@ -126,7 +129,30 @@ public void fillInnerParts() {
 
         entryPane = new EntryPane(expenseEntryPanel, incomeEntryPanel);
         entryPanePlaceholder.getChildren().add(entryPane.getRoot());
-
+        entryPane.getExpenses().setOnSelectionChanged((EventHandler<Event>) t -> {
```
Comment (EmilyOng) [inline src/main/java/seedu/pennywise/ui/MainWindow.java:132]:
```suggestion
        entryPane.getExpenses().setOnSelectionChanged((EventHandler<Event>) evt -> {
```

File: src/main/java/seedu/pennywise/ui/MainWindow.java [hunk 3]
```diff
@@ -126,7 +129,30 @@ public void fillInnerParts() {
...
+                    this.currGraphPanel.getGraphType(),
+                    true);
+            CommandResult expenditureCommandResult = new CommandResult(
+                    "",
+                    false,
+                    false,
+                    expenditureGraphConfig);
+            this.updateGraph(expenditureCommandResult);
+        });
+        entryPane.getIncome().setOnSelectionChanged((EventHandler<Event>) t -> {
```
Comment (EmilyOng) [inline src/main/java/seedu/pennywise/ui/MainWindow.java:144]:
```suggestion
        entryPane.getIncome().setOnSelectionChanged((EventHandler<Event>) evt -> {
```

**Review by EmilyOng — APPROVED** [review]
LGTM, sorry for late reply!
